### PR TITLE
Delete

### PR DESCRIPTION
**Pull request by AhmedAbusoud**
Feature 6: Delete movie

### CODE REVIEW

**Review by kabulsoud — COMMENTED** [review]
I think all should be good

**Comment by MSaadWaheed** [comment]
I don't see anything wrong with the code. Looks good

**Review by MSaadWaheed — APPROVED** [review]
The code looks good to me, Just make sure the tests are passing.

**Review by ZaidJ2003 — APPROVED** [review]
looks good to me

**Pull request merged**
